default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: car_rentals_dev

test:
  <<: *default
  database: car_rentals_test


production:
  url: <%= ENV['DATABASE_URL'] %>